import pandas as pd
from time import sleep


def read_csv_data(fileName):
    print('Reading data from csv.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.2)
    print('.', end='')
    sleep(.5)
    dFrame = pd.read_csv(fileName, index_col=0)
    data = dFrame.to_dict("split")
    data = dict(zip(data['index'], data['data']))
    print('Done.\n')
    sleep(.3)
    return data
